name: Deploy static HTML to Azure Web App - anjuandshibin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload static HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: static-html
          path: path/to/your/static/html/files

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: static-html
          path: downloaded-static-html

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'anjuandshibin'
          slot-name: 'production'
          package: downloaded-static-html
